name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4
    
    - name: 登录DcokerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_NAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: 构建Docker image
      run: docker build . --file Dockerfile.private --tag jinwen0428/rsshub-private:$(date +%s)
