name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4
    
    - name: 登录Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_NAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: 构建并推送Docker image
      run: |
        SHA=${{ github.sha }}
        docker build . --file Dockerfile.private --tag jinwen0428/rsshub-private:${SHA:0:7} --tag jinwen0428/rsshub-private:latest
        docker push jinwen0428/rsshub-private:${SHA:0:7}
        docker push jinwen0428/rsshub-private:latest
